#!/bin/bash

echo "🚀 Moniqo - Push to GitHub"
echo "=========================="
echo ""
echo "Repository: https://github.com/karanchopda/Moniqo.git"
echo ""
echo "⚠️  You need to authenticate first!"
echo ""
echo "Choose your authentication method:"
echo ""
echo "1. GitHub CLI (Recommended - Easiest)"
echo "   brew install gh"
echo "   gh auth login"
echo "   git push -u origin main"
echo ""
echo "2. Personal Access Token"
echo "   - Go to: https://github.com/settings/tokens"
echo "   - Generate new token (classic)"
echo "   - Select 'repo' scope"
echo "   - Copy the token"
echo "   - Run: git push -u origin main"
echo "   - Username: karanchopda"
echo "   - Password: [paste your token]"
echo ""
echo "3. SSH Keys"
echo "   - Run: ssh-keygen -t ed25519 -C 'your_email@example.com'"
echo "   - Run: cat ~/.ssh/id_ed25519.pub | pbcopy"
echo "   - Add to: https://github.com/settings/keys"
echo "   - Run: git remote set-url origin git@github.com:karanchopda/Moniqo.git"
echo "   - Run: git push -u origin main"
echo ""
echo "📚 For detailed instructions, see: AUTHENTICATION_SETUP.md"
echo ""
echo "After authenticating, run:"
echo "  git push -u origin main"
echo ""
